### ISSUE TITLE
0.10.0: @formepdf/core Node entry imports missing pkg-node/forme.js (package ships only pkg/)

### ISSUE THREAD

**Issue by largeant** [danmolitor/forme#10]
**What happened?**

After upgrading `@formepdf/core` from `0.9.1` to `0.10.0`, the server crashes on boot with:

```
error: Cannot find module '../pkg-node/forme.js' from
'node_modules/@formepdf/core/dist/index.js'
```

The published 0.10.0 tarball ships only `pkg/` (the bundler/browser wasm-pack target). The Node entry `dist/index.js` imports from `../pkg-node/forme.js`, and that directory is not present in the installed package — so any Node consumer fails immediately at import time, before rendering anything.

`package.json` declares `"files": ["dist/", "pkg/", "pkg-node/"]`, so it looks like the `pkg-node/` (wasm-pack `--target nodejs`) build step was skipped or excluded before publish. The browser entry (`dist/browser.js`, which imports from `pkg/`) is unaffected.

Grep against the installed package:

```
dist/index.js:4:   import { render_pdf as wasmRenderPdf } from '../pkg-node/forme.js';
dist/index.js:60:  const { render_pdf_with_layout } = await import('../pkg-node/forme.js');
dist/index.js:90:  const { render_template_pdf } = await import('../pkg-node/forme.js');
...
```

```
$ ls node_modules/@formepdf/core
dist  package.json  pkg  README.md          # no pkg-node/
```

**What did you expect?**

`import { ... } from '@formepdf/core'` to resolve under Node (Bun/Node.js) the same way it did on 0.9.1 — i.e. the published tarball includes `pkg-node/forme.js` (the wasm-pack nodejs target) so `dist/index.js` can load the WASM module.

**Reproduction**

No TSX needed — the failure happens at module load, before any rendering:

```ts
// repro.ts
import { renderPdf } from "@formepdf/core"
console.log(typeof renderPdf)
```

```bash
bun add @formepdf/core@0.10.0 @formepdf/react@0.10.0
bun repro.ts
# error: Cannot find module '../pkg-node/forme.js' from
# 'node_modules/@formepdf/core/dist/index.js'
```

Same error with `node --experimental-vm-modules` / `node` directly.

**Output**

No PDF is produced — import fails before any render call. Stack trace above.

**Environment**
- Forme version: `@formepdf/core@0.10.0`, `@formepdf/react@0.10.0` (worked on `0.9.1`)
- Node version: Bun 1.3.11 (also fails on Node 20 / 22)
- OS: Windows 11 (also expected to fail on Linux/macOS — it's a missing-file-in-tarball issue, not platform-specific)

**Comment by danmolitor** [comment]
@largeant Thanks for raising this, I'll get a fix out today.

**Comment by danmolitor** [comment]
@largeant I just published 0.10.1 - let me know if that fixes your issue.
